ggg_user:
    resource: "@GGGUserBundle/Resources/config/routing.yml"
    prefix:   /

ggg_notices:
    resource: "@GGGNoticesBundle/Resources/config/routing.yml"
    prefix:   /

ggg_user_inscription:
    pattern: /inscription
    defaults : { _controller: GGGUserBundle:Default:inscription }

login:
    pattern:  /login
    defaults: { _controller: GGGUserBundle:Security:login }


login_check:
    pattern:  /login_check

logout:
    pattern:  /logout 